
Expr    ::= <Expr> '+' <Term>
        |   <Expr> '-' <Term>
        |   <Term>

// 项
Term    ::= <Term> '*' <Factor>
        |   <Term> '/' <Factor>
        |   <Factor>

//Factor  ::= '(' <Expr> ')' '[' NUM ']'
//        |   '(' <Expr> ')' '(' ARGV ')'
//        |   '(' <Expr> ')'
//        |   NAME '[' NUM ']'
//        |   NAME '(' ARGV ')'
//        |   NAME
//        |   NUM

// 因子
Factor  ::= '(' <Expr> ')'
        |   NAME
        |   NUM